# Generated by Django 5.0 on 2023-12-08 08:40

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999999999, max_length=8, validators=[bboard.models.validate_positive, django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Это мы сами написали'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{3,}$')], verbose_name='Товар'),
        ),
    ]
