# Generated by Django 5.0 on 2023-12-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_id_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='currency',
            field=models.CharField(choices=[('kzt', 'Тенге'), ('usd', 'Доллар')], default='kzt', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='bb',
            name='list_field',
            field=models.TextField(blank=True, null=True, verbose_name='Лист для заполнения'),
        ),
    ]
