# Generated by Django 4.2.7 on 2024-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('put_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
